---
title: "preprocess_nitrate_2025"
output: html_document
date: "2025-12-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
```

```{r}
nitrate_2025 <- readxl::read_excel('/Users/xindilin/Desktop/2024 summer/groundwater_pesticide/data/nitrate_NO3_total_2025.xlsx')
```

```{r}
nitrate_2025 <-  nitrate_2025[,c("WI Unique Well #","Section","Township","Range","Range Direction","Well Bottom (ft.)","Static Water Level (ft.)","Casing Bottom (ft.)","Well Use","Sample Collection Date","Sample Analytical Result Amount")]

colnames(nitrate_2025) <-  c("WellID","Section","Township","Range","Range.Direction","Well Bottom (ft.)","Static Water Level (ft.)","Casing Bottom (ft.)","Well Use","Sample Collection Date","Sample Analytical Result Amount")

nitrate_2025 <- na.omit(nitrate_2025)
nitrate_2025$Township <- as.numeric(nitrate_2025$Township)
nitrate_2025$Range <- as.numeric(nitrate_2025$Range)
nitrate_2025$Section <- as.numeric(nitrate_2025$Section)
```

```{r}
file_path <- "/Users/xindilin/Desktop/2024 summer/groundwater_pesticide/data/plss_covariates.csv"
command <- paste("brctl download", shQuote(file_path))
system(command)
plss_covariates <- read.csv(file_path)
```

```{r}
nitrate_2025 <-  left_join(nitrate_2025, plss_covariates,by=c("Township","Range.Direction","Range","Section"))
```

```{r}
nitrate_2025 <- na.omit(nitrate_2025)
```


```{r}
nitrate_2025$crop = NULL
nitrate_2025$crop_type = NULL
nitrate_2025$SampleDate = as.Date(as.POSIXct(nitrate_2025$`Sample Collection Date`, tz = "UTC"))
nitrate_2025$SampleYear = year(nitrate_2025$SampleDate)
nitrate_2025$SampleMonth = month(nitrate_2025$SampleDate)
nitrate_2025$concentration_plus = nitrate_2025$`Sample Analytical Result Amount` + 0.5
nitrate_2025 = nitrate_2025[!nitrate_2025$`Well Use` %in% c("ANODE","DRILLHOLE/DRY HOLE","HEAT EXCHANGE","LOOP"),]
nitrate_2025 = nitrate_2025[!nitrate_2025$crop_type_combine %in% c("Other Crop"),]
nitrate_2025 = nitrate_2025[!nitrate_2025$taxorder %in% c("Ultisols"),]
nitrate_2025$WellDepth =  (nitrate_2025$`Well Bottom (ft.)` - nitrate_2025$`Casing Bottom (ft.)`)/2 + nitrate_2025$`Casing Bottom (ft.)`
nitrate_2025$crop_type_combine = relevel(factor(nitrate_2025$crop_type_combine),ref = "Forest")
nitrate_2025$drainagecl = factor(nitrate_2025$drainagecl,levels = c("Very poorly drained","Poorly drained","Somewhat poorly drained","Moderately well drained","Well drained","Somewhat excessively drained","Excessively drained"))
nitrate_2025$WellUse = nitrate_2025$`Well Use`
nitrate_2025$`Well Use` = NULL
nitrate_2025$StaticLevel = nitrate_2025$`Static Water Level (ft.)`
nitrate_2025$`Static Water Level (ft.)` = NULL
nitrate_2025$cafolog = log(nitrate_2025$cafo+1)
nitrate_2025$WellUse = as.factor(nitrate_2025$WellUse)
```

```{r}
# median of the measurement of the same well at the same month
# median is more stable than average 
nitrate_2025 <- nitrate_2025 %>%
  group_by(WellID,SampleYear,SampleMonth) %>%
  summarise(
  concentration_plus_median = median(concentration_plus),
    across(-concentration_plus, first) # Keep all other columns with their first value
  )
```

```{r}
write.csv(nitrate_2025, "/Users/xindilin/Desktop/2024 summer/groundwater_pesticide/data/data_Nitrate_with_covar_median_well_2025.csv",row.names = FALSE)
```

